carrier_image: C:/Users/jshul/OneDrive/Pictures/watch_ad2.jpg
#injected_image: C:/Users/jshul/OneDrive/Pictures/stopsign.png # Path to injected/attack image
injected_image: C:/Users/jshul/OneDrive/Pictures/black_sphere.jpg
duration: 20.0 # Units: seconds

# Injection Type:
injection_config:
  injection_type: "lab" # Choices: [log, lab]
  color_deltaE: 10.0 # Units: L space difference
  mask_pattern: "full" # Choices: [full, edges]

#injection_config:
#  injection_type: "log"
#  contrast: 1.0

# Spatial offset
dx: 0 # Units: Pixels
dy: 0 # Units: Pixels
scale: 1.0 # Units: None

# Temporal offset
vibration_config:
  amp: 0 # Units: Pixels
  freq: 0 # Units: Hz
  angle: 0 # Units: degrees

monitor_id: 0 # Monitor choice (primary or secondary)

attack_method: # Choices: [fixed, lfm, contrast_injection]
  type: fixed
  fps: 165.0 # Units: Hz
