carrier_image: C:/Users/Jeff/Pictures/watch_ad2.jpg
injected_image: C:/Users/Jeff/Documents/Research/event_attack/injection_photos/hidden_images/stopsign.png # Path to injected/attack image

duration: 20.0 # Units: seconds

# Injection Type:
injection_config:
  injection_type: "lab" # Choices: [log, lab]
  color_deltaE: 10.0 # Units: L space difference
  mask_pattern: "full" # Choices: [full, edges]


# Spatial offsets
dx: 0.0 # Units: Pixels
dy: 0.0 # Units: Pixels
scale: 1.0 # Units: None

# Temporal offset0
vibration_config:
  amp: 0 # Units: Pixels
  freq: 0 # Units: Hz
  angle: 0 # Units: degrees

monitor_id: 0 # Monitor choice (primary or secondary)

attack_method:
  type: lfm # Choices: [fixed, lfm, contrast_injection]
  start_freq: 60.0 # Units: Hz
  end_freq: 165.0 # Units: Hz
  sweep_duration: 0.5 # Units: seconds
  reverse_sweep: True # Units: boolean (True/False)
